include: package:flutter_lints/flutter_lints.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_returning_null_for_future: true
    - avoid_types_as_parameter_names: true
    - cancel_subscriptions: true
    - close_sinks: true
    - empty_constructor_bodies: true
    - hash_and_equals: true
    - no_duplicate_case_values: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - prefer_final_fields: true
    - sort_child_properties_last: true
    - sort_constructors_first: true
    - unawaited_futures: true
    - unnecessary_brace_in_string_interps: true

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
